Add post pre-caching disk usage check (#597)
This commit consists of checking for disk space usage after pre-caching is completed successfully to address the potential kubelet garbage collection problem that can result in the deletion of the pre-cached images (thus nullifying the entire pre-caching job).

The commit contains the following changes:
- refactor pre-cache/check_space script to check disk space for both pre and post pre-caching.
- update the pre-cache/precache.sh script to include post pre-caching disk usage.
- refactor controllers/precache.go and controllers/templates/precache-templates.go source files to remove the spaceRequired environment variable references and assignments. The spaceRequired parameter has been added to the pre-cache-spec ConfigMap previously.
- update unit and kuttl tests accordingly to remove spaceRequired environment variable references.

Signed-off-by: Sharat Akhoury <sakhoury@redhat.com>

diff --git a/pre-cache/check_space b/pre-cache/check_space
--- a/pre-cache/check_space
+++ b/pre-cache/check_space
@@ -1,15 +1,34 @@
-#!/bin/bash
-set -e
+./#!/bin/bash
 
-APISERVER=https://kubernetes.default.svc
-SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
-TOKEN=$(cat ${SERVICEACCOUNT}/token)
-CACERT=${SERVICEACCOUNT}/ca.crt
-high=$(curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/nodes/${NODE_NAME}/proxy/configz | \
-            chroot /host jq '.kubeletconfig.imageGCHighThresholdPercent')
-size=$(df /host/var/lib/ | awk '{ print $2 }' | sed -n '2p')
-used=$(df /host/var/lib/ | awk '{ print $3 }' | sed -n '2p')
-echo "highThresholdPercent: $high diskSize:$size used:$used"
-rc=$(awk "BEGIN {avail=${size}/100.0*${high}-${used} ; print avail<${SPACE_REQUIRED}*1024*1024}")
-[ $rc -ne 0 ] && echo "ERROR: not enough space for precaching"
-exit $rc
+cwd=$(dirname "$0")
+. $cwd/common
+
+validate_disk_space() {
+    local space_required=${1:-0}
+    local rv=1
+
+    APISERVER=https://kubernetes.default.svc
+    SERVICEACCOUNT=/var/run/secrets/kubernetes.io/serviceaccount
+    TOKEN=$(cat ${SERVICEACCOUNT}/token)
+    CACERT=${SERVICEACCOUNT}/ca.crt
+    high=$(curl --cacert ${CACERT} --header "Authorization: Bearer ${TOKEN}" -X GET ${APISERVER}/api/v1/nodes/${NODE_NAME}/proxy/configz | \
+                chroot /host jq '.kubeletconfig.imageGCHighThresholdPercent')
+    size=$(df /host/var/lib/ | awk '{ print $2 }' | sed -n '2p')
+    used=$(df /host/var/lib/ | awk '{ print $3 }' | sed -n '2p')
+
+    log_debug "highThresholdPercent: $high diskSize:$size used:$used"
+    log_debug "spaceRequired: ${space_required} GiB"
+
+    if [[ $space_required -gt 0 ]]; then
+        rv=$(awk "BEGIN {avail=${high}/100.0*${size}-${used} ; print (avail<${space_required}*1024*1024)}")
+    else
+        rv=$(awk "BEGIN {avail=${high}/100.0*${size}-${used} ; print (avail<=0)}")
+    fi
+    [ $rv -ne 0 ] && log_error "not enough space for precaching"
+    return $rv
+}
+
+if [[ "${BASH_SOURCE[0]}" = "${0}" ]]; then
+    validate_disk_space ${1:-0}
+    exit $?
+fi
